import { Product, ProductCategory, CustomerReview } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'racing-titular-2024',
    name: 'Camiseta Racing Club Titular 2024',
    team: 'Racing Club',
    league: 'Liga Profesional',
    category: 'racing',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 35000,
    originalPrice: 42000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Home'],
    images: [
      'https://placehold.co/600x800/003087/FFFFFF?text=racing-titular-2024',
      'https://placehold.co/600x800/003087/FFFFFF?text=racing-titular-2024-back',
    ],
    description:
      'Camiseta oficial titular de Racing Club temporada 2024. Azul y blanco, tecnología DryFit, escudo bordado. La Academia en tu piel.',
    features: [
      'Tecnología DryFit transpirable',
      'Escudo Racing bordado oficial',
      'Tela 100% poliéster de alta calidad',
      'Corte atlético moderno',
      'Apto lavado a máquina hasta 30°C',
    ],
    badge: 'Sale',
    inStock: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: '2',
    slug: 'racing-alternativa-2024',
    name: 'Camiseta Racing Club Alternativa 2024',
    team: 'Racing Club',
    league: 'Liga Profesional',
    category: 'racing',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 35000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Away'],
    images: [
      'https://placehold.co/600x800/E3051B/FFFFFF?text=racing-alternativa-2024',
      'https://placehold.co/600x800/E3051B/FFFFFF?text=racing-alternativa-2024-back',
    ],
    description:
      'Versión alternativa de Racing Club 2024. Rojo intenso con detalles en blanco, corte moderno. Ideal para hinchar desde las tribunas.',
    features: [
      'Tecnología DryFit transpirable',
      'Escudo Racing bordado oficial',
      'Rojo intenso Racing Club',
      'Slim fit moderno',
      'Apto lavado a máquina',
    ],
    badge: 'New',
    inStock: true,
    rating: 4.8,
    reviewCount: 187,
  },
  {
    id: '3',
    slug: 'argentina-titular-2024',
    name: 'Camiseta Argentina Titular 2024',
    team: 'Selección Argentina',
    league: 'AFA',
    category: 'selecciones',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 38000,
    originalPrice: 45000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Home', 'Away'],
    images: [
      'https://placehold.co/600x800/74ACDF/FFFFFF?text=argentina-titular-2024',
      'https://placehold.co/600x800/74ACDF/FFFFFF?text=argentina-titular-2024-back',
    ],
    description:
      'Camiseta de la Selección Argentina, campeona del mundo. Celeste y blanco, parche de campeón. Las tres estrellas que conquistaron Qatar 2022.',
    features: [
      'Tecnología Dri-FIT ADV',
      'Escudo AFA bordado con 3 estrellas',
      'Parche oficial Campeón del Mundo',
      'Corte atlético championship',
      'Certificado de autenticidad',
    ],
    badge: 'New',
    inStock: true,
    rating: 5.0,
    reviewCount: 428,
  },
  {
    id: '4',
    slug: 'argentina-tercera-2024',
    name: 'Camiseta Argentina Tercera 2024',
    team: 'Selección Argentina',
    league: 'AFA',
    category: 'selecciones',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 38000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Third'],
    images: [
      'https://placehold.co/600x800/5B2D8E/FFFFFF?text=argentina-tercera-2024',
      'https://placehold.co/600x800/5B2D8E/FFFFFF?text=argentina-tercera-2024-back',
    ],
    description:
      'Tercera camiseta de la Selección Argentina 2024. Color violeta exclusivo, edición limitada que se agota rápido. Un diseño único e icónico.',
    features: [
      'Edición limitada coleccionable',
      'Color violeta exclusivo',
      'Escudo AFA bordado con 3 estrellas',
      'Tejido premium breathable',
      'Numerado y certificado',
    ],
    badge: 'Limited',
    inStock: true,
    rating: 4.9,
    reviewCount: 203,
  },
  {
    id: '5',
    slug: 'real-madrid-titular-2025',
    name: 'Camiseta Real Madrid Titular 2024/25',
    team: 'Real Madrid',
    league: 'La Liga',
    category: 'europa',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 40000,
    originalPrice: 48000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Home', 'Away', 'Third'],
    images: [
      'https://placehold.co/600x800/FFFFFF/003087?text=real-madrid-titular-2025',
      'https://placehold.co/600x800/FFFFFF/003087?text=real-madrid-titular-2025-back',
    ],
    description:
      'Camiseta oficial del Real Madrid temporada 2024/25. Blanco puro, tecnología Adidas HEAT.RDY para máximo rendimiento. Los campeones de Europa.',
    features: [
      'Tecnología Adidas HEAT.RDY',
      'Escudo Real Madrid bordado oficial',
      'Blanco puro icónico',
      'Certificado de autenticidad',
      'Apto lavado a máquina',
    ],
    badge: 'Sale',
    inStock: true,
    rating: 4.8,
    reviewCount: 247,
  },
  {
    id: '6',
    slug: 'barcelona-titular-2025',
    name: 'Camiseta Barcelona Titular 2024/25',
    team: 'FC Barcelona',
    league: 'La Liga',
    category: 'europa',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 40000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Home', 'Away'],
    images: [
      'https://placehold.co/600x800/A50044/FFFFFF?text=barcelona-titular-2025',
      'https://placehold.co/600x800/A50044/FFFFFF?text=barcelona-titular-2025-back',
    ],
    description:
      'Camiseta oficial del FC Barcelona 2024/25. Azulgrana clásico con detalles dorados. El Barça que vuelve a rugir en Europa.',
    features: [
      'Tecnología Nike Dri-FIT ADV',
      'Escudo FC Barcelona bordado',
      'Azulgrana con detalles dorados',
      'Slim fit moderno',
      'Material reciclado 100%',
    ],
    badge: 'New',
    inStock: true,
    rating: 4.7,
    reviewCount: 183,
  },
  {
    id: '7',
    slug: 'manchester-city-titular-2025',
    name: 'Camiseta Manchester City Titular 2024/25',
    team: 'Manchester City',
    league: 'Premier League',
    category: 'europa',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 40000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Home', 'Away', 'Third'],
    images: [
      'https://placehold.co/600x800/6CADDF/FFFFFF?text=manchester-city-titular-2025',
      'https://placehold.co/600x800/6CADDF/FFFFFF?text=manchester-city-titular-2025-back',
    ],
    description:
      'Camiseta del Manchester City 2024/25. Celeste cielo con detalles en blanco, Puma. El equipo de Guardiola que domina la Premier League.',
    features: [
      'Tecnología Puma ULTRAWEAVE',
      'Escudo City bordado oficial',
      'Celeste Sky Blue icónico',
      'Regular fit performance',
      'Certificado OEKO-TEX',
    ],
    inStock: true,
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: '8',
    slug: 'psg-titular-2025',
    name: 'Camiseta PSG Titular 2024/25',
    team: 'Paris Saint-Germain',
    league: 'Ligue 1',
    category: 'europa',
    categoryId: null,
    garmentType: 'Camisetas',
    price: 40000,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableVersions: ['Home', 'Away', 'Third'],
    images: [
      'https://placehold.co/600x800/1C1C3C/E3051B?text=psg-titular-2025',
      'https://placehold.co/600x800/1C1C3C/E3051B?text=psg-titular-2025-back',
    ],
    description:
      'Camiseta del Paris Saint-Germain 2024/25. Azul marino con franja roja, Nike Dri-FIT. El Paris que seduce al mundo con su estilo único.',
    features: [
      'Tecnología Nike Dri-FIT',
      'Escudo PSG bordado oficial',
      'Azul marino con franja roja',
      'Slim fit parisino',
      'Apto lavado a máquina',
    ],
    badge: 'New',
    inStock: true,
    rating: 4.7,
    reviewCount: 134,
  },
]

export const categories: ProductCategory[] = [
  {
    id: 'racing',
    slug: 'racing',
    name: 'Racing Club',
    description: 'La Academia, titular y alternativa',
    image: 'https://placehold.co/500x350/003087/FFFFFF?text=Racing+Club',
    count: 2,
    visible: true,
    sortOrder: 0,
  },
  {
    id: 'selecciones',
    slug: 'selecciones',
    name: 'Selecciones',
    description: 'Argentina titular y tercera',
    image: 'https://placehold.co/500x350/74ACDF/FFFFFF?text=Selecciones',
    count: 2,
    visible: true,
    sortOrder: 0,
  },
  {
    id: 'europa',
    slug: 'europa',
    name: 'Europa',
    description: 'Real Madrid, Barcelona, City, PSG',
    image: 'https://placehold.co/500x350/1C1C3C/E3051B?text=Europa',
    count: 4,
    visible: true,
    sortOrder: 0,
  },
  {
    id: 'ligas-locales',
    slug: 'ligas-locales',
    name: 'Ligas Locales',
    description: 'Próximamente',
    image: 'https://placehold.co/500x350/4B5563/FFFFFF?text=Próximamente',
    count: 0,
    visible: true,
    sortOrder: 0,
    comingSoon: true,
  },
]

export const reviews: CustomerReview[] = [
  {
    id: '1',
    name: 'Martín Acuña',
    initials: 'MA',
    rating: 5,
    date: '10 Mar 2025',
    text: 'La titular de Racing llegó perfecta, igual a la que usan en el Cilindro. El escudo bordado se ve espectacular y la tela es muy cómoda. ¡Aguante La Academia!',
    product: 'Racing Club Titular 2024',
    verified: true,
  },
  {
    id: '2',
    name: 'Valentina Cruz',
    initials: 'VC',
    rating: 5,
    date: '18 Mar 2025',
    text: 'Pedí la Argentina para mi hermano y quedó re contento. La calidad es increíble, el parche de campeón y las tres estrellas se ven perfectas. 100% recomendado.',
    product: 'Argentina Titular 2024',
    verified: true,
  },
  {
    id: '3',
    name: 'Lucas Ferreiro',
    initials: 'LF',
    rating: 5,
    date: '25 Mar 2025',
    text: 'La alternativa roja de Racing es una obra de arte. Me la puse para el clásico y todos me preguntaban dónde la compré. Llegó en dos días, impecable.',
    product: 'Racing Club Alternativa 2024',
    verified: true,
  },
  {
    id: '4',
    name: 'Sofía Moreno',
    initials: 'SM',
    rating: 4,
    date: '2 Abr 2025',
    text: 'La Argentina tercera violeta es una locura, diseño único. Llegó bien embalada y el talle M me quedó perfecto según la guía. Muy buena experiencia de compra.',
    product: 'Argentina Tercera 2024',
    verified: true,
  },
  {
    id: '5',
    name: 'Tomás Ibáñez',
    initials: 'TI',
    rating: 5,
    date: '15 Abr 2025',
    text: 'Compré la del Real Madrid y es idéntica a la original. La textura de la tela y el acabado del escudo son de primera. Ya hice el segundo pedido con la del Barcelona.',
    product: 'Real Madrid Titular 2024/25',
    verified: true,
  },
  {
    id: '6',
    name: 'Camila Ríos',
    initials: 'CR',
    rating: 5,
    date: '22 Abr 2025',
    text: 'Uso Carpi para comprar camisetas hace meses y nunca me fallaron. Siempre llegan antes de lo esperado y la calidad es impecable. Los mejores del rubro.',
    product: 'FC Barcelona Titular 2024/25',
    verified: true,
  },
]
